### PR TITLE
Return only max of open-sky metric by default

### PR DESCRIPTION
**Pull request by leifdenby**
Previously both the max and average value of the open-sky metric was returned, however a sensible default for any metric should return only a single scalar value. Based on Antonissen 2018
(http://resolver.tudelft.nl/uuid:d868273a-b028-4273-8380-ff1628ecabd5) the maximum value of the open-sky metric is the default characteristic used.

### CODE REVIEW

**Comment by leifdenby** [comment]
And this one too @martinjanssens if you have a chance :) Thank you

**Comment by martinjanssens** [comment]
That sounds good to me. Two small points:
- I usually find the average open-sky area size is more expressive for distinguishing between scenes which are similar (especially for LES fields without large, clear-sky swaths); perhaps we should make a note of that in the documentation?
- Maybe we should treat this as an excuse to also pick up #58, which I think is now the remaining inconsistency in how we interface metric computation?

**Comment by leifdenby** [comment]
> * I usually find the average open-sky area size is more expressive for distinguishing between scenes which are similar (especially for LES fields without large, clear-sky swaths); perhaps we should make a note of that in the documentation?

Great, good idea. Yes I've just added that :) What do you think to the changes now?

Also, sorry for the late reply. My autumn ended up being too full of things, so I'm only just returning to this now :)

**Comment by leifdenby** [comment]
> * Maybe we should treat this as an excuse to also pick up

Yes! I agree. I don't have time at the moment to do this though, but if you (or someone else?) does, that would be great!

**Review by martinjanssens — APPROVED** [review]
Wonderful, thanks for picking this up again and finishing it :) This looks perfect to me. I'll see if I find time in January for the spectral metrics, but I think I'm suffering from similar time division problems as you are...

**Pull request merged**
