### PR TITLE
Update metrics and docstrings for functions that are resolution and domain-size dependent

### PR DESCRIPTION
**Pull request by martinjanssens**
In response to #1 and #49, I've started on this. The first commit modifies the length-scale functions in `cloudmetrics/objects/metrics/geometry.py` and updates the tests accordingly.

### CODE REVIEW

**Comment by martinjanssens** [comment]
@leifdenby I would be curious to hear what you think about these two points, if you find you have time.  :)

**Comment by leifdenby** [comment]
Thanks for working on this @martinjanssens! I think we might have misunderstood each other :) My intention with https://github.com/cloudsci/cloudmetrics/issues/49 was only to add to the documentation that the values returned are in length-scales of "number of pixels". I'm not sure how intuitive it is to return the scales as normalised by the number of pixels in the input, but maybe I'm thinking about this incorrectly. I think it would be good to chat about this to brainstorm a bit.

**Comment by martinjanssens** [comment]
Ooooh, right, I'm fine with that. Let's at least do what you suggest for this release, since it's going to be much quicker to implement; we can always revisit this in our bigger planned discussion on resolution/domain size invariance. :)

**Comment by martinjanssens** [comment]
Have a look if you think it's better now. I've removed normalisation and references to it, and now only have docstrings that tell you how to convert the length scales that come out of these metrics to physical units. I've also given the other docstrings a once-over; they look like they're in quite good shape!

**Comment by leifdenby** [comment]
> Ooooh, right, I'm fine with that. Let's at least do what you suggest for this release, since it's going to be much quicker to implement; we can always revisit this in our bigger planned discussion on resolution/domain size invariance. :)

Yes, sounds good. I'm definitely open to changing this in the future, and your ideas sound great!

**Comment by leifdenby** [comment]
Thanks for working on this @martinjanssens :) I probably would have put the README modifications in a separate pull-request, but nevermind :)

**Pull request merged**
