### PR TITLE
Refactoring cloud object scales metrics

### PR DESCRIPTION
**Pull request by leifdenby**
I've rewritten the "object scales" routines to separate out the labeling of objects (from the cloud mask) from the routines that compute the object properties. I've done this so that other labeling approaches can easily be added. I haven't quite worked out how the API should be for computing these metrics directly from a cloud-mask, it might be nice to have an interface with something like `cloudmetrics.mean_object_length_scale(cloud_mask, labeling_method="1-connectivity")`, other labeling methods (like watershed) could then be introduced later. Note sure if this is this the right approach... At least the labeling method should be made explicit I think.

I've also put the individual object metrics (mean length, max length, etc) into individual functions.

Progress:
- [x] refactor into separate functions and add some caching to avoid recalculation of object properties
- [ ] work out how/whether to introduce functions which operate directly on the object mask
- [x] add test for max length-scale of objects
- [ ] work out how to handle periodic domains
- [x] add tests mean length-scale
- [x] add tests for mean eccentricity
- [x] add tests for perimeter length
- [x] add test mask for periodic domain
- [ ] add docstrings for all functions

### CODE REVIEW

**Comment by leifdenby** [comment]
@martinjanssens it would be great to have your thoughts on this pull-request too. I've created tests for all the object scales, including a tests which should capture the periodic domains. Something I'm a bit unsure about here: Is it reasonable to use the approach you've implemented (where the data is copied in x and y-directions) for dealing with periodic domains in this case? That would add extra objects and skew the statistics I think, no? Maybe it would be better to implement a `create_periodic_ghost_cells` which uses https://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.pad after removing part of the mask that doesn't touch the boundary?

**Comment by martinjanssens** [comment]
I really like the `cloudmetrics.object_metric(cloud_object_labels)` setup, with the labels and region properties only being calculated once in a run. This does require one extra pre-processing step on the part of the user (first creating the labels), but maybe it's good to keep that explicit in example scripts, so the user knows what is going on. It would break the consistency of the `cloudmetrics.metric(cloud_mask)` syntax. I don't mind that for the object metrics, but then we should make sure these are easy to understand as being a separate group of metrics.

**Comment by martinjanssens** [comment]
Regarding periodic BCs, I think the implementation we have should work correctly with the setup we have in this refactored branch, if the object labelling is always performed on a `cloud_mask` that has had the `make_periodic_function` applied to it, for fields with periodic BCs. This function will move objects that exist e.g. both on the north and the south boundary to the south boundary and cut/paste the bit that resides on the north boundary below the southern boundary (into an extended domain). This is necessary to make the labelling understand that such objects are actually a single object, and the size statistics should be applied to those "single" objects. @leifdenby do you think that's the correct approach?

**Comment by leifdenby** [comment]
>  It would break the consistency of the `cloudmetrics.metric(cloud_mask)` syntax. I don't mind that for the object metrics, but then we should make sure these are easy to understand as being a separate group of metrics.

I agree, it would best to make the "kind" of a metric explicit. Maybe what we should do is have `cloudmetrics.mask_metrics.{metric_name}(...)` and `cloudmetrics.object_metrics.{metric_name}(...)`? I hadn't gotten straight in my head how many of the metrics work on masks, on objects, scalar fields, etc. Maybe once we're done refactoring each we can consider (on a separate issue) the best way of providing a unified interface? It would be nice to provide "sensible defaults" to compute all the metrics (maybe just the defaults that you originally had would suffice, but we make them more explicit).

**Comment by leifdenby** [comment]
> Regarding periodic BCs, I think the implementation we have should work correctly with the setup we have in this refactored branch, if the object labelling is always performed on a `cloud_mask` that has had the `make_periodic_function` applied to it, for fields with periodic BCs. This function will move objects that exist e.g. both on the north and the south boundary to the south boundary and cut/paste the bit that resides on the north boundary below the southern boundary (into an extended domain). This is necessary to make the labelling understand that such objects are actually a single object, and the size statistics should be applied to those "single" objects. @leifdenby do you think that's the correct approach?

Yes, that was what I was thinking too :) I hadn't read through your `make_periodic_function` in detail and didn't realise that it *moves* objects that exist on the boundary. That was really cool, well done for making that! I'll finish up this pull-request to use that function and make the periodic tests pass.

**Comment by leifdenby** [comment]
@martinjanssens I've changed my mind a bit since working on this this morning: I think we do need to expose the metric calculations that are object-based in a way that these can be calculated directly on object-masks rather than only expose the functions which operator on labelled objects.

The reason is that it isn't possible (at least with what we currently have) to correct an object-labels array for periodic boundary conditions, instead that mask needs correcting and then new labels can be computed. This means we can't have a function like `max_length_scale(labelled_objects, periodic_domain=[True,False])` unless we turn the `labelled_objects` into a mask again, and then label objects again, which seems bit hacky to me 😄 (and also means we're labeling objects twice...)

What I've added (hopefully you think this is ok) is a set of wrapper functions which expose the object-based metrics so they can be computed directly on the cloud-masks. The naming convention I've come up with is for a object-metric named `{op}_{measure}` the mask-based function is called `{op}_cloud_{measure}`, e.g. for `mean_perimeter_length` this becomes `mean_cloud_perimeter_length`. What do you think of is? Of course the imports I've written could be written using introspection to automatically make the metrics available in `skimage.measure.regionprops` available, but maybe that's for another day :)

I just want to add a bit more to the docstring, maybe you can help me with the following:
- [ ] what are the units of `eccentricity`? And what are the limits of the values (is it [0:1] for round to infinitely long)?

**Review by martinjanssens — COMMENTED** [review]
Really nice work here again. I agree that it's not totally obvious how we should structure the eventual package. It depends on how much flexibility we want to (or care about) providing, and balancing that with making things as easy as possible for the user. I agree that the object metric computation functions in ``cloudmetrics/objects/metrics.py`` need to operate on the objects directly, and that we should apply ``make_periodic_field`` only once. Your solution here is really neat, as it allows everything and thus allows us to push the problem into the future, when we're done refactoring :) My feeling is that we might just want to eventually keep things simple and present the user with a single way of doing things, i.e. we choose between 
- Making the metric function interfaces uniform and handling all necessary processing in the background or 
- Making the code progression explicit: A typical cloudmetrics user script would then first compute the cloud mask, apply periodic BCs, label the cloud mask, compute the objects and finally compute the metric functions operate directly on the required fields/derived properties, all in the user's code. That would be messier for the user, but probably makes it easier to understand what the code does.

I think we can defer the final terminology choice until after that discussion as well :) For now, I think it makes sense to merge this in!

**Comment by martinjanssens** [comment]
@leifdenby we're converging on a structure here where the object metrics all operate on a single object mask per image, which in turn acts on a single labelled cloud mask per image. If we want to maximise the use of this structure, I think we'd actually want to put _all_ the object-based metrics in this format, i.e we should include.
  - `cop`
  - `scai`
  - `rdf`
  - `csd`
  - `iorgPoisson`
 in this structure. If you agree on this, I can pick up your branch and add those to the code you already have in this PR. Alternatively, we could merge this in now and I'll add separate PRs for these metrics. What do you think?

**Pull request merged**
