### PR TITLE
Performance of open_sky function

### PR DESCRIPTION
**Pull request by observingClouds**
I came across #68 and optimised the open_sky function for my own purposes and thought I share it here.

What would be left to do to before even considering this PR:

- [x] testing functionality
- [x] testing performance
- [x] add numba to requirements.txt
- [ ] find a way to add back the unsupported debug_plot
- [ ] find a way to add back the NotImplementedError

### CODE REVIEW

**Comment by observingClouds** [comment]
I experimented with numba but it actually did not improve the performance. The refactoring of the function did however increase the performance by about 19000 times. I tested it for a random field of 100x1000 and got 1.05s and 54µs. I guess that's a win 🤣 Numba also does not improve the performance for larger fields (e.g. 10000x1000).

```python
import numpy as np
import cloud metrics
EXAMPLE_MASK=np.random.randint(0,1,(100,1000))
%timeit cloudmetrics.mask.open_sky(EXAMPLE_MASK)
# 54 µs ± 627 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

**Comment by observingClouds** [comment]
@martinjanssens @leifdenby please have a look. The PR is ready to be merged from my side.

**Review by martinjanssens — APPROVED** [review]
Haha, a speedup of 19,000 times sounds pretty good. The code looks good to me :) So if it's not `numba` (and therefore not `prange`), what gives the performance enhancement in the end? Rewriting the if statements inside the loops?

Thanks a lot for doing this @observingClouds :)

**Comment by observingClouds** [comment]
To be honest I'm not 100% sure but I think it is the replacement of some of the `np.where` functions.

**Pull request merged**
